# Generated by Django 4.2.1 on 2023-06-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_language_song_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.BooleanField(default=False),
        ),
    ]
