# Generated by Django 4.2.1 on 2023-06-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
    ]
